implementado backend de creacion de proyecto
alabarque/Apprendiendo pull request #5
Opened 2021-07-10 18:48 UTC by jlsoto85

2021-07-12 02:22 UTC, agustin-labarque commented on src/main/java/com/proyecto/apprendiendo/services/NewProjectService.java
> +                                 .retoId(newProjectDTO.getRetoId())
Javi, recien lo veo, pero el reto te quedo en castellano.
Creo que le pondria como nombre "challenge" en ingles.

2021-07-12 02:24 UTC, alabarque commented on src/main/java/com/proyecto/apprendiendo/services/NewProjectService.java
> +                                 .retoId(newProjectDTO.getRetoId())
Javi, recien lo veo, pero el reto te quedo en castellano. Creo que le pondria como nombre "challenge" en ingles, mismo para las otras ocurrencias.

2021-08-02 23:25 UTC, alabarque approved these changes

2021-08-02 23:25 UTC, alabarque commented on src/main/java/com/proyecto/apprendiendo/entities/dtos/NewProjectDTO.java
> +    private Long classroomId;
Si estas pasando aca el id de la clase, tiene sentido entonces pasarlo por parametro en el controller?

O por el contrario, tiene sentido pasar el parametro en el dto/json?

2021-08-02 23:25 UTC, alabarque commented on src/main/java/com/proyecto/apprendiendo/services/NewProjectService.java
> +    private ProjectRepository projectRepository;
Ojo aca que te falto el constructor, o bien te falto poner @AllArgsContructor

2021-08-02 23:26 UTC, alabarque requested changes

2021-08-02 23:26 UTC, alabarque commented on src/main/java/com/proyecto/apprendiendo/services/NewProjectService.java
> +    private ProjectRepository projectRepository;
Agrego comment porque toque approve sin querer en vez de request changes

2021-08-04 22:48 UTC, alabarque approved these changes

2021-08-04 22:48 UTC, merged